name: Publish docs

on: [workflow_dispatch]

jobs:
  publish_docs_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET Core 9.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Build & Deploy docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./build.sh --no-color publish-docs-gh-actions

