name: Publish Lamar IoC Nugets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build Lamar.sln --configuration Release

    - name: Pack
      run: |
        dotnet pack src/Lamar/Lamar.csproj --configuration Release --no-build --output ${{ github.workspace }}/artifacts
        dotnet pack src/Lamar.Microsoft.DependencyInjection/Lamar.Microsoft.DependencyInjection.csproj --configuration Release --no-build --output ${{ github.workspace }}/artifacts

    - name: Publish to NuGet
      run: dotnet nuget push "${{ github.workspace }}/artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
